version: '3'

services:
  weekly-report:
    image: weekly-report
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/app/data
    env_file: ./.env

networks:
  default:
    external:
      name: nginx-net